#!/bin/bash
set -euo pipefail

toolchain_file_name=riscv64-toolchain.cmake

build_dir_name=build-riscv64

app_name=ninvaders

rootfs_file_name=rootfs

required_commands=(cmake cpio)
for cmd in "${required_commands[@]}"; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "Error: '${cmd}' is not installed."
    echo "Please install it and run this script again."
    exit 1
  fi
done


cmake -S . -B ${build_dir_name} -DCMAKE_TOOLCHAIN_FILE=${toolchain_file_name}

cmake --build ${build_dir_name}

mkdir -p cpio/ninvaders/usr/bin
cp ${build_dir_name}/${app_name} cpio/ninvaders/usr/bin/${app_name}

cd cpio/ninvaders
find . | cpio -o -H newc > ../${app_name}.cpio
cd ../..

#cpio以下にrootfs.cpioがある場合，ninvaders.cpioをインストールする
if [ -f cpio/${rootfs_file_name}.cpio ]
then
  cat cpio/${app_name}.cpio cpio/${rootfs_file_name}.cpio > cpio/${rootfs_file_name}_with_${app_name}.cpio
else
  echo "cpio/${rootfs_file_name}.cpio is not found."
fi